config/routes.rb
Rails.application.routes.draw do

  resources :companies
  resources :property_utilities
  # get 'tenancy/sign_up'
  concern :attachable do
    resources :attachments, only: :create
  end

  resources :tenancies do
    resources :criminal_records
    resources :additional_tenants
    get :archived
    get :unarchived
    member do
      get :complete
      get :roll_next_year
      get :send_payment_items
      get :tenancy_payment_schedule
    end
  end
  resources :features
  # resources :tenants
  resources :events do
    collection do
      get :reminder
      get :done_reminder
    end
  end
  devise_for :users
  resources :rooms
  resources :listings
  resources :landlords do
    member do
      get :landlord_booking_report
      get :filter_booking_report
      get :send_booking_report
    end
  end
  resources :properties, concerns: [:attachable] do
    collection do
      get :get_properties
      get :get_available_properties
    end
    get :get_rooms
    get :get_filter_rooms
    get :edit_attachment
    patch :update_attachment
    member do
      resource :email_tenants_compliance_documents, only: :create, controller: 'properties/email_tenants_compliance_documents'
      get :resend_statement_report
      get :filter_landlord_statement
      get :filter_annual_landlord_statement
      get :generate_landlord_annual_statement
      get :send_email_to_tenants
    end
    resources :property_expenses, only: %w(new create destroy) do
      collection do
        get :filter_expense
      end
    end
    resources :rooms, only: [:new, :create, :index, :edit, :update] do
      member do
        get :sync
        get :sync_rightmove
        get :sync_zoopla
      end
    end
  end
  delete "remove_property_image/:property_id/:id", :to => "properties#remove_property_image", as: :remove_property_image
  get 'properties/:property_id/set_tenancy_form', to: 'properties#set_tenancy_form', as: :set_tenancy_form
  post 'properties/:property_id/set_tenancy', to: 'properties#set_tenancy', as: :set_tenancy
  get 'tenancies/:tenancy_id/mail_tenancy_dashboard_link', to: 'tenancies#mail_tenancy_dashboard_link', as: :mail_tenancy_dashboard_link

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :messages
  resources :users
  post 'users/create', to: 'users#create', as: :create_new_user
  get 'users/new', to: 'users#new', as: :add_new_user

  get 'events_by_date', to: 'events#events_by_date'
  get 'welcome/index'
  get 'property/units/:status', to: 'welcome#properties', as: :property_units
  get 'calendar/index'

  get 'tenancies/tenancy_dashboard/:u_id', to: 'tenancies#tenancy_dashboard', as: :tenancy_dashboard
  #get 'tenancy/sign_up' #I do not know where to use it :)

  get 'tenancies/booking_form/:u_id', to: 'tenancies#booking_form', as: :booking_form
  post 'tenancies/submit_booking_form/:u_id', to: 'tenancies#submit_booking_form', as: :submit_booking_form

  get 'tenancies/agreement_form/:u_id', to: 'tenancies#agreement_form', as: :agreement_form
  post 'tenancies/submit_agreement_form/:u_id', to: 'tenancies#submit_agreement_form', as: :submit_agreement_form

  get 'tenancies/document_confirmation_form/:u_id', to: 'tenancies#document_confirmation_form', as: :document_confirmation_form
  post 'tenancies/document_confirmation/:u_id', to: 'tenancies#document_confirmation', as: :document_confirmation

  get 'tenancies/final_submission/:u_id', to: 'tenancies#final_submission', as: :submit_tenancy_form

  get 'tenancies/tenancy_dashboard/closed/:u_id', to: 'tenancies#closed_dashboard', as: :closed_dashboard

  get 'guarantors/guarantor_dashboard/:u_id', to: 'guarantors#guarantor_dashboard', as: :guarantor_dashboard

  get 'guarantors/agreement_form/:u_id', to: 'guarantors#agreement_form', as: :guarantor_agreement_form
  post 'guarantors/submit_agreement_form/:u_id', to: 'guarantors#submit_agreement_form', as: :guarantor_submit_agreement_form
  post 'confirm_tenancy_signed/:u_id', to: "guarantors#confirm_tenancy_signed", as: :confirm_signed_tenancy
  get 'guarantors/tenancy_agreement_form/:u_id', to: 'guarantors#tenancy_agreement_form', as: :guarantor_tenancy_agreement_form
  get 'guarantors/complete_guarantor_agreement/:u_id', to: 'guarantors#complete_guarantor_agreement', as: :complete_guarantor_agreement
  get 'mail_guarantor_dashboard_link', to: "guarantors#mail_guarantor_dashboard_link", as: :mail_guarantor_dashboard_link

  get 'reporting/index'
  get 'reporting/compliance_documents', to: 'reporting#compliance_documents', as: :reporting_compliance_documents
  get 'reporting/list_of_people_in_arrears', :to => 'reporting#list_of_people_in_arrears', as: :list_of_people_in_arrears
  get 'reporting/viewings', :to => 'reporting#viewings', as: :viewings
  get 'reporting/property_listings', :to => 'reporting#property_listings', as: :property_listings
  get 'reporting/tenancies', to: 'reporting#tenancies', as: :reporting_tenancies
  get 'reporting/combined_landlord_report', to: 'reporting#combined_landlord_report', as: :reporting_combined_landlord
  get "/print", to: "reporting#print_arrears", as: :print_arrears_report
  get "/send-arrear-report", to: "reporting#send_arrear_report", as: :send_arrear_report
  # get "/monthly-reports", to: "reporting#monthly_statement_report", as: :monthly_statement_reports
  # get "/send-property-report", to: "reporting#send_property_report", as: :send_property_report
  get "/set_custom_report_date", to: "reporting#set_custom_report_date", as: :set_custom_report_date
  get "/print-compliance-document", to: "reporting#print_compliance_report", as: :print_compliance_report
  get "/annual-commission-report", to: "reporting#annual_commission_report", as: :annual_commission_report
  get "/annual-rent-report", to: "reporting#annual_rent_report", as: :annual_rent_report
  get "/print-annual-rent-report", to: "reporting#print_annual_rent_report", as: :print_annual_rent_report
  get "/print-commission-income-report", to: "reporting#print_annual_commission_report", as: :print_annual_commission_report
  get "/sales-analysis-report", to: "reporting#sales_analysis_report", as: :sales_analysis_report
  get "/availability", to: "reporting#available_room", as: :available_room
  get "/print-availability", to: "reporting#print_available_room", as: :print_available_room
  get "/filter_sales_analysis_report", to: "reporting#filter_sales_analysis_report", as: :filter_sales_analysis_report
  get "print-sales-analysis-report", to: "reporting#print_sales_analysis_report", as: :print_sales_analysis_report
  get 'tenancy_payment_item_form/:tenancy_id', :to => 'tenancies#tenancy_payment_item_form', as: :tenancy_payment_item_form
  get "/monthly-payment-report", to: "reporting#monthly_payment_report", as: :monthly_payment_report
  get "/print-monthly-payment-report", to: "reporting#print_monthly_payment_report", as: :print_monthly_payment_report
  get "generate-monthly-payment-report",  to: "reporting#generate_monthly_payment_report", as: :generate_monthly_payment_report
  post 'tenancy_payment_item/:tenancy_id', :to => 'tenancies#tenancy_payment_item', as: :tenancy_payment_item
  delete 'tenancy_payment_item_delete/:item_id', :to => 'tenancies#tenancy_payment_item_delete', as: :tenancy_payment_item_delete
  resources :errors

  get 'filter_rooms', :to => 'rooms#filter_rooms', as: :filter_rooms

  resources :tenancy_staff_conversations, only: [:index, :new, :create] do
    resources :tenancy_staff_messages, only: [:index, :new, :create]
  end
  resources :tenancy_staff_messages

  ## admin section
  resource :admin, only: [] do
    get '/', to: 'admins#index'
    get '/generic-document', to: 'admins#generic_document'
    get '/system-signature', to: 'admins#system_signature'
    get :new_generic_document
    post :create_generic_document
    get :edit_generic_document
    delete :destroy_generic_document
    post :update_generic_document
    get :assign_generic_document
    get '/manage-automation-mail', to:'admins#manage_automation_mail'
    post :create_manage_automation_mail
    patch '/admin/update_manage_automation_mail/:id', to:'admins#update_manage_automation_mail', as: :update_manage_automation_mail
    get :open_automation_mail
    get :get_mail_options
    get :edit_automation_mail
    get :update_manage_automation
    get :sync_setting
    patch :update_sync_setting
    delete :delete_automation_mail
  end

  get 'tenancy_staff_messages/reply_form/:message_id', :to => 'tenancy_staff_messages#reply_form', as: :tenancy_staff_reply_form

  resources :landlord_staff_conversations, only: [:index, :new, :create] do
    resources :landlord_staff_messages, only: [:index, :new, :create]
  end
  resources :landlord_staff_messages

  get 'landlord_staff_messages/reply_form/:message_id', :to => 'landlord_staff_messages#reply_form', as: :landlord_staff_reply_form

  namespace :api do
    namespace :v1 do
      resources :properties, only: :index
    end
  end

  root 'welcome#index'
end

app/models/landlord.rb
class Landlord < ApplicationRecord
  mount_base64_uploader :landlord_signature, AttachmentUploader, file_name: -> (l) { "landlord-sig-"+l.id.to_s }

  ##
  enum partnership_format: ['Complete Partner', 'Support Partner', 'Tenancy Partner', 'Booking Partner','Listing Partner', 'Owned']
  validates :contact_name, presence: true
  validates :email, presence: true
  validates :partnership_format, presence: true

  has_many :properties, dependent: :destroy
  has_many :rooms, through: :properties, dependent: :destroy
  has_many :tenancies, through: :rooms
  has_many :reports
  has_many :landlord_documents, dependent: :destroy
  accepts_nested_attributes_for :landlord_documents, reject_if: :all_blank, allow_destroy: true

  has_many :landlord_staff_conversations
  has_many :sender_landlord_staff_messages, as: :sender, class_name: 'LandlordStaffMessage'
  has_many :receiver_landlord_staff_messages, as: :receiver, class_name: 'LandlordStaffMessage'


  filterrific(
    default_filter_params: { sorted_by: 'contact_name_asc' },
    available_filters: [
      :sorted_by,
      :search_query
    ]
  )

  terms_query = "LOWER(landlords.contact_name) LIKE ? OR LOWER(landlords.company_name) LIKE ?"
  scope :search_query, ->(query) {
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map{|term| term.gsub(/\*$/, '')}.map{|term| "%#{term}%"}
    num_or_conditions = 2
    where(
      terms.map {  |term|
        terms_query
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, ->(sort_option) {
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^contact_name/
      order("landlords.contact_name #{direction}")
    when /^partner_type/
      order("landlords.partnership_format #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  def self.options_for_sorted_by
    [
      ['Contact Name (A-Z)', 'contact_name_asc'],
      ['Contact Name (Z-A)', 'contact_name_desc'],
      ['Partner Type (A-Z)', 'partner_type_asc'],
      ['Partner Type (Z-A)', 'partner_type_desc']
    ]
  end

  def landlord_name
    if company_name != ''
      company_name
    else
      contact_name
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include Pagy::Backend
  require 'csv'
  require 'securerandom'

  def index
    @all_rooms = Room.joins(:property).ids
    @rooms = Room.joins(:property)
    @filterrific = initialize_filterrific(
      @rooms,
      params[:filterrific],
      select_options: {
        sorted_by: @rooms.options_for_sorted_by
      },
      persistence_id: "rooms_key",
      default_filter_params: {},
      sanitize_params: true,
      ) || return
    @rooms = @filterrific.find

    respond_to do |format|
      format.js do
        @pagy, @rooms = pagy(@rooms, items: 100)
      end
      format.html do
        @pagy, @rooms = pagy(@rooms, items: 100)
      end
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"listings.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
      format.pdf do
        status = ''
        if @filterrific.room_availability.present?
          status = 0 if @filterrific.room_availability.room_available == '1'
          status = 1 if @filterrific.room_availability.room_booked == '1'
          status = 2 if @filterrific.room_availability.room_complete == '1'
          status = 3 if @filterrific.room_availability.room_expired == '1'
        end

        selected_year = !params[:filterrific].nil? ? params[:filterrific][:room_availability][:search_by_year_range] : @current_year
        pdf = ListingPdf.new(@rooms, selected_year, status)

        if params[:mail] == "false"
          send_data pdf.render, filename: 'listings.pdf', type: 'application/pdf'
        else
          filename = "#{"listings-"+SecureRandom.hex(8)+".pdf"}"
          pdf.render_file(filename)
          TenancyMailer.list_mailer(filename).deliver
          redirect_to(reset_filterrific_url(format: :html)) && return
        end
      end
    end
  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{e.message}"
    redirect_to(reset_filterrific_url(format: :html)) && return
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def get_tenancies_btwn_years(room, filterrific_year, status)
    tenancies = room.tenancies.not_failed.where("tenancies.year= ?", filterrific_year).order(:tenancy_start)
    tenancies = tenancies.where("tenancies.booking_status = ?", status) if [1, 2].include?(status)
    if tenancies.count >= 1
      {tenancies: tenancies, tenant_present: true}
    else
      {tenancies: "", tenant_present: false}
    end
  end

  def available_for_the_year(year, room)
    tenancies = check_room_completed_availability(year, room)
    return tenancies.count > 0 ? false : true
  end

  def check_room_completed_availability(year, room)
    date = Date.today
    month = date.month
    cur_year = month > 9 ? (date.year + 1) : (date.year)
    tenancies = room.tenancies.where(year: year, booking_status: 2).where.not(
      'DATE(tenancy_end) < ?', ("31/08/#{cur_year.to_i}").to_date
    )
    return tenancies
  end

  def last_completed_date(room)
    date = Date.today
    month = date.month
    cur_year = month > 9 ? (date.year + 1) : (date.year)
    year  = @current_year
    tenancies = room.tenancies.where(year: year, booking_status: 2).where(
      'DATE(tenancy_end) < ?', ("31/08/#{cur_year.to_i}").to_date
    )
    last_date = tenancies.count > 0 ? tenancies.order('tenancy_end asc').last.tenancy_end : ''
    return last_date
  end

  def property_titles(room)
    if room.property.address_line_2?
      fullproperty = "#{room.property.property_name}, #{room.property.address_line_2}"
    else
      fullproperty = room.property.property_name
    end
    return fullproperty
  end
end

app/views/listings/_list.html.erb
<div id="filterrific_results">
  <div class="table-responsive">
    <table class="table table-striped table-hover list" aria-describedby="listings-table">
      <thead>
        <tr>
          <th><input type="checkbox" id="selectAll" ></th>
          <th>No.</th>
          <th>Property</th>
          <th>Room</th>
          <th>List <br>Price</th>
          <th>Booked <br>Price</th>
          <th class="tenancy-header">Type</th>
          <th class="tenancy-header">Start</th>
          <th class="tenancy-header">End</th>
          <th class="tennancy-header list_name">Name</th>
          <th class="tenancy-header">Mobile</th>
          <th class="tenancy-header list_email">Email</th>
          <th class="tenancy-header t_icon"><i class="fas fa-edit" title="Booking form completed"></i></th>
          <th class="tenancy-header t_icon"><i class="fas fa-signature" title="Signed Tenancy"></i></th>
          <th class="tenancy-header t_icon"><i class="fas fa-user-lock" title="Guarantor"></i></th>
          <th title="Advanced Rent">AvR</th>
          <th title="Deposit Paid">DPT</th>
          <th></th>
        </tr>
      </thead>
      <% sort_year = (@filterrific.room_availability.present? && @filterrific.room_availability.search_by_year_range != "") ? @filterrific.room_availability.search_by_year_range : @current_year  %>
      <% status = '' %>
      <% if @filterrific.room_availability.present? %>
        <% status = 0  if @filterrific.room_availability.room_available == '1' %>
        <% status = 1 if @filterrific.room_availability.room_booked == '1' %>
        <% status = 2 if @filterrific.room_availability.room_complete == '1' %>
      <% end %>
      <tbody>
        <% @rooms.uniq.each do |room| %>
          <% tenancies = get_tenancies_btwn_years(room, sort_year, status) %>
          <%- if tenancies[:tenant_present] -%>
            <%- tenancies[:tenancies].each_with_index do |tenancy, index| -%>
              <tr class="<%= tenancy.booking_status %>">
                <%- if index == 0 -%>
                  <td class="small"><%= check_box_tag "room_ids[]", room.id, false, class: 'selectable' %></td>
                  <td class="small"><%= link_to room.property.number, property_path(room.property) %></td>
                  <td><%= link_to room.property.street, property_path(room.property) %></td>
                  <td class="small"><%= link_to room_display_type(room.number), room_path(room) %></td>
                <%- else -%>
                  <%- 4.times do -%>
                    <td></td>
                  <%- end -%>
                <%- end -%>
                <td>£<%= room.list_price %></td>
                <td><%= tenancy.payment_amount? ? "£#{tenancy.payment_amount}" : ''  %></td>
                <td><%= tenant_type_icon(tenancy.tenancy_is)&.html_safe %></td>
                <td class="start-date"><%= l(tenancy.tenancy_start, format: :nice, default: '') %></td>
                <td class="end-date"><%= l(tenancy.tenancy_end, format: :nice, default: '') %></td>
                <td class="list_name">
                  <%= link_to tenancy_path(tenancy) do %>
                    <%= tenancy.tenant_name.truncate(15, omission: '...') %>
                    <% if tenancy.additional_tenants.present? %>
                      <br>
                      <% tenancy.additional_tenants.each do |additional_tenant| %>
                        <%= "#{additional_tenant.first_name} #{additional_tenant.surname}".truncate(15, omission: '...') %>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= tel_to(tenancy.mobile) %></td>
                <td class="list_email"><%= mail_to tenancy.email, tenancy.email.truncate(22, omission: '...') %></td>
                <td class="t_icon"><%= yes_no(tenancy.form_submitted) %></td>
                <td class="t_icon"><%= yes_no(tenancy.signed_tenancy_agreement) %></td>
                <td class="t_icon">
                  <% if tenancy.is_guarantor_available == true %>
                    <%= yes_no(tenancy&.guarantor&.complete_guarantor_agreement) %>
                  <% else %>
                    <span class="badge badge-danger">N/A</span>
                  <% end %>
                </td>
                <td class="t_icon">
                  <% if tenancy.tenancy_is == 0 %>
                    <%= yes_no(tenancy.tenancy_payment_items.where(item: 'AvR').where.not(date_paid: nil).where('amount_paid >= amount_due').present?) %>
                  <% else %>
                    <span class="badge badge-danger">N/A</span>
                  <% end %>
                </td>
                <td class="t_icon">
                  <%= yes_no(tenancy.deposit_paid) %>
                </td>
                <%- if index == 0 -%>
                  <% available = available_for_the_year(sort_year, room) %>
                  <td>
                    <% if available %>
                      <%= link_to 'Book', set_tenancy_form_path(room.property.id, room_id: room.id), :data => {:turbolinks => false}, class: 'btn small btn-success', :remote => true %>
                    <% end %>
                  </td>
                <%- else -%>
                  <td></td>
                <%- end -%>
              </tr>
            <%- end -%>
          <%- else -%>
            <tr>
              <td><%= check_box_tag "room_ids[]", room.id, false, class: 'selectable' %></td>
              <td><%= link_to room.property.number, property_path(room.property) %></td>
              <td><%= link_to room.property.street, property_path(room.property) %></td>
              <td><%= link_to room_display_type(room.number), room_path(room) %></td>
              <td>£<%= room.list_price %></td>
              <td></td>
              <td colspan="11"></td>
              <td>
                <% available = available_for_the_year(sort_year, room) %>
                <%- if available %>
                  <%= link_to 'Book', set_tenancy_form_path(room.property.id, room_id: room.id), :data => {:turbolinks => false}, class: 'btn small btn-success', :remote => true %>
                <%- end -%>
              </td>
            </tr>
          <%- end -%>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagy-container">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
  </div>
</div>
<div class="modal fade" id="set-tenancy-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>

app/views/listings/index.csv.erb
<%= CSV.generate_line(['Property', 'Room No', 'List Price', 'Booked Price', 'Size', 'Name', 'Type', 'Start', 'End', 'Mobile', 'Email', 'Availability', 'Accepted', 'Signed'], { col_sep: ",", force_quotes: false }) %>
<%- @rooms.uniq.each do |room| -%>
  <% if room.tenancies.count >= 1 %>
    <% sort_year = (@filterrific.room_availability.present? && @filterrific.room_availability.search_by_year_range != "") ? @filterrific.room_availability.search_by_year_range : @current_year  %>
    <% status = '' %>
    <% if @filterrific.room_availability.present? %>
      <% status = 0 if @filterrific.room_availability.room_available == '1' %>
      <% status = 1 if @filterrific.room_availability.room_booked == '1' %>
      <% status = 2 if @filterrific.room_availability.room_complete == '1' %>
    <% end %>
    <% tenancies = get_tenancies_btwn_years(room, sort_year, status) %>
    <% if tenancies[:tenant_present] %>
      <% tenancies[:tenancies].each_with_index do |tenancy, index| %>
        <%= CSV.generate_line([room.property.property_name.gsub(",","-"), tenancy.room.number, room.list_price, tenancy.payment_amount, tenancy.room.property.number_of_bedrooms, (tenancy.tenant_name == "" ? "N/A" : tenancy.tenant_name), tenancy.tenancy_is_nice_name, l(tenancy.tenancy_start, format: :nice, default: ''), l(tenancy.tenancy_end, format: :nice, default: ''), (tenancy.mobile == "" ? "N/A" : tenancy.mobile), (tenancy.email == "" ? "N/A" : tenancy.email), (room.availability? ? 'Yes' : 'No'), (tenancy.accept_agreement? ? 'Yes' : 'No'), (tenancy.signed_tenancy_agreement? ? 'Yes' : 'No')], { col_sep: ",", force_quotes: false }) -%>
      <% end %>
    <% else %>
      <%= CSV.generate_line([room.property.property_name.gsub(",","-"), room.number, room.list_price, ' ', room.property.number_of_bedrooms, ' ', ' ', ' ', ' ', ' ', ' ', (room.availability? ? 'Yes' : 'No'), 'N/A', 'N/A'], { col_sep: ",", force_quotes: false }) -%>
    <% end %>
  <% else %>
    <%= CSV.generate_line([room.property.property_name.gsub(",","-"), room.number, room.list_price, ' ', room.property.number_of_bedrooms, ' ', ' ', ' ', ' ', ' ', ' ', (room.availability? ? 'Yes' : 'No'), 'N/A', 'N/A'], { col_sep: ",", force_quotes: false }) -%>
  <% end %>
<%- end -%>

app/views/listings/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { rooms: @rooms })
) %>
$("#filterrific_results").html("<%= js %>");
<% year = (@filterrific.room_availability.present? && @filterrific.room_availability.search_by_year_range.present?) ? @filterrific.room_availability.search_by_year_range : @current_year %>

$('#sort-by-years').val("<%= year %>")
$(document).ready(function(){
  $("#filterrific_room_availability_room_available").click(function(){
    $('#filterrific_room_availability_room_booked').prop("checked", false);
    $('#filterrific_room_availability_room_complete').prop("checked", false);
  });
  $("#filterrific_room_availability_room_booked").click(function(){
    $('#filterrific_room_availability_room_available').prop("checked", false);
    $('#filterrific_room_availability_room_complete').prop("checked", false);
  });
  $("#filterrific_room_availability_room_complete").click(function(){
    $('#filterrific_room_availability_room_available').prop("checked", false);
    $('#filterrific_room_availability_room_booked').prop("checked", false);
  });
});



$(document).ready(function() {
  if ($("#sort-by-years").val()  !=  ""){
    var year = $("#sort-by-years").val();
    $(".years-filters").find("[data-years-range='" + year + "']").addClass("btn btn-primary");
    $("#sort-by-years").trigger('click');
  }
  $("#selectAll").select_all();
  var format = "";
  var mail = false;
  $('.get-listings').on('click', function(){
    format = $(this).data("format");
    mail = $(this).data("mail");
    select_all_rooms(format, mail);
    $('#filterrific_filter').submit();
  });
  function select_all_rooms(format, mail){
    var room_ids = [];
    $('.selectable:checkbox:checked').each(function(){
      room_ids.push($(this).val());
    });
    $('#filterrific_with_room_ids').val([room_ids]);
    $('#filterrific_filter').append("<input type='hidden' name='format' value='"+format+"' />");
    $('#filterrific_filter').append("<input type='hidden' name='mail' value='"+mail+"' />");
  }
});``