config/routes.rb
Rails.application.routes.draw do

  resources :companies
  resources :property_utilities
  # get 'tenancy/sign_up'
  concern :attachable do
    resources :attachments, only: :create
  end

  resources :tenancies do
    resources :criminal_records
    resources :additional_tenants
    get :archived
    get :unarchived
    member do
      get :complete
      get :roll_next_year
      get :send_payment_items
      get :tenancy_payment_schedule
    end
  end
  resources :features
  # resources :tenants
  resources :events do
    collection do
      get :reminder
      get :done_reminder
    end
  end
  devise_for :users
  resources :rooms
  resources :listings
  resources :landlords do
    member do
      get :landlord_booking_report
      get :filter_booking_report
      get :send_booking_report
    end
  end
  resources :properties, concerns: [:attachable] do
    collection do
      get :get_properties
      get :get_available_properties
    end
    get :get_rooms
    get :get_filter_rooms
    get :edit_attachment
    patch :update_attachment
    member do
      resource :email_tenants_compliance_documents, only: :create, controller: 'properties/email_tenants_compliance_documents'
      get :resend_statement_report
      get :filter_landlord_statement
      get :filter_annual_landlord_statement
      get :generate_landlord_annual_statement
      get :send_email_to_tenants
    end
    resources :property_expenses, only: %w(new create destroy) do
      collection do
        get :filter_expense
      end
    end
    resources :rooms, only: [:new, :create, :index, :edit, :update] do
      member do
        get :sync
        get :sync_rightmove
        get :sync_zoopla
      end
    end
  end
  delete "remove_property_image/:property_id/:id", :to => "properties#remove_property_image", as: :remove_property_image
  get 'properties/:property_id/set_tenancy_form', to: 'properties#set_tenancy_form', as: :set_tenancy_form
  post 'properties/:property_id/set_tenancy', to: 'properties#set_tenancy', as: :set_tenancy
  get 'tenancies/:tenancy_id/mail_tenancy_dashboard_link', to: 'tenancies#mail_tenancy_dashboard_link', as: :mail_tenancy_dashboard_link

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :messages
  resources :users
  post 'users/create', to: 'users#create', as: :create_new_user
  get 'users/new', to: 'users#new', as: :add_new_user

  get 'events_by_date', to: 'events#events_by_date'
  get 'welcome/index'
  get 'property/units/:status', to: 'welcome#properties', as: :property_units
  get 'calendar/index'

  get 'tenancies/tenancy_dashboard/:u_id', to: 'tenancies#tenancy_dashboard', as: :tenancy_dashboard
  #get 'tenancy/sign_up' #I do not know where to use it :)

  get 'tenancies/booking_form/:u_id', to: 'tenancies#booking_form', as: :booking_form
  post 'tenancies/submit_booking_form/:u_id', to: 'tenancies#submit_booking_form', as: :submit_booking_form

  get 'tenancies/agreement_form/:u_id', to: 'tenancies#agreement_form', as: :agreement_form
  post 'tenancies/submit_agreement_form/:u_id', to: 'tenancies#submit_agreement_form', as: :submit_agreement_form

  get 'tenancies/document_confirmation_form/:u_id', to: 'tenancies#document_confirmation_form', as: :document_confirmation_form
  post 'tenancies/document_confirmation/:u_id', to: 'tenancies#document_confirmation', as: :document_confirmation

  get 'tenancies/final_submission/:u_id', to: 'tenancies#final_submission', as: :submit_tenancy_form

  get 'tenancies/tenancy_dashboard/closed/:u_id', to: 'tenancies#closed_dashboard', as: :closed_dashboard

  get 'guarantors/guarantor_dashboard/:u_id', to: 'guarantors#guarantor_dashboard', as: :guarantor_dashboard

  get 'guarantors/agreement_form/:u_id', to: 'guarantors#agreement_form', as: :guarantor_agreement_form
  post 'guarantors/submit_agreement_form/:u_id', to: 'guarantors#submit_agreement_form', as: :guarantor_submit_agreement_form
  post 'confirm_tenancy_signed/:u_id', to: "guarantors#confirm_tenancy_signed", as: :confirm_signed_tenancy
  get 'guarantors/tenancy_agreement_form/:u_id', to: 'guarantors#tenancy_agreement_form', as: :guarantor_tenancy_agreement_form
  get 'guarantors/complete_guarantor_agreement/:u_id', to: 'guarantors#complete_guarantor_agreement', as: :complete_guarantor_agreement
  get 'mail_guarantor_dashboard_link', to: "guarantors#mail_guarantor_dashboard_link", as: :mail_guarantor_dashboard_link

  get 'reporting/index'
  get 'reporting/compliance_documents', to: 'reporting#compliance_documents', as: :reporting_compliance_documents
  get 'reporting/list_of_people_in_arrears', :to => 'reporting#list_of_people_in_arrears', as: :list_of_people_in_arrears
  get 'reporting/viewings', :to => 'reporting#viewings', as: :viewings
  get 'reporting/property_listings', :to => 'reporting#property_listings', as: :property_listings
  get 'reporting/tenancies', to: 'reporting#tenancies', as: :reporting_tenancies
  get 'reporting/combined_landlord_report', to: 'reporting#combined_landlord_report', as: :reporting_combined_landlord
  get "/print", to: "reporting#print_arrears", as: :print_arrears_report
  get "/send-arrear-report", to: "reporting#send_arrear_report", as: :send_arrear_report
  # get "/monthly-reports", to: "reporting#monthly_statement_report", as: :monthly_statement_reports
  # get "/send-property-report", to: "reporting#send_property_report", as: :send_property_report
  get "/set_custom_report_date", to: "reporting#set_custom_report_date", as: :set_custom_report_date
  get "/print-compliance-document", to: "reporting#print_compliance_report", as: :print_compliance_report
  get "/annual-commission-report", to: "reporting#annual_commission_report", as: :annual_commission_report
  get "/annual-rent-report", to: "reporting#annual_rent_report", as: :annual_rent_report
  get "/print-annual-rent-report", to: "reporting#print_annual_rent_report", as: :print_annual_rent_report
  get "/print-commission-income-report", to: "reporting#print_annual_commission_report", as: :print_annual_commission_report
  get "/sales-analysis-report", to: "reporting#sales_analysis_report", as: :sales_analysis_report
  get "/availability", to: "reporting#available_room", as: :available_room
  get "/print-availability", to: "reporting#print_available_room", as: :print_available_room
  get "/filter_sales_analysis_report", to: "reporting#filter_sales_analysis_report", as: :filter_sales_analysis_report
  get "print-sales-analysis-report", to: "reporting#print_sales_analysis_report", as: :print_sales_analysis_report
  get 'tenancy_payment_item_form/:tenancy_id', :to => 'tenancies#tenancy_payment_item_form', as: :tenancy_payment_item_form
  get "/monthly-payment-report", to: "reporting#monthly_payment_report", as: :monthly_payment_report
  get "/print-monthly-payment-report", to: "reporting#print_monthly_payment_report", as: :print_monthly_payment_report
  get "generate-monthly-payment-report",  to: "reporting#generate_monthly_payment_report", as: :generate_monthly_payment_report
  post 'tenancy_payment_item/:tenancy_id', :to => 'tenancies#tenancy_payment_item', as: :tenancy_payment_item
  delete 'tenancy_payment_item_delete/:item_id', :to => 'tenancies#tenancy_payment_item_delete', as: :tenancy_payment_item_delete
  resources :errors

  get 'filter_rooms', :to => 'rooms#filter_rooms', as: :filter_rooms

  resources :tenancy_staff_conversations, only: [:index, :new, :create] do
    resources :tenancy_staff_messages, only: [:index, :new, :create]
  end
  resources :tenancy_staff_messages

  ## admin section
  resource :admin, only: [] do
    get '/', to: 'admins#index'
    get '/generic-document', to: 'admins#generic_document'
    get '/system-signature', to: 'admins#system_signature'
    get :new_generic_document
    post :create_generic_document
    get :edit_generic_document
    delete :destroy_generic_document
    post :update_generic_document
    get :assign_generic_document
    get '/manage-automation-mail', to:'admins#manage_automation_mail'
    post :create_manage_automation_mail
    patch '/admin/update_manage_automation_mail/:id', to:'admins#update_manage_automation_mail', as: :update_manage_automation_mail
    get :open_automation_mail
    get :get_mail_options
    get :edit_automation_mail
    get :update_manage_automation
    get :sync_setting
    patch :update_sync_setting
    delete :delete_automation_mail
  end

  get 'tenancy_staff_messages/reply_form/:message_id', :to => 'tenancy_staff_messages#reply_form', as: :tenancy_staff_reply_form

  resources :landlord_staff_conversations, only: [:index, :new, :create] do
    resources :landlord_staff_messages, only: [:index, :new, :create]
  end
  resources :landlord_staff_messages

  get 'landlord_staff_messages/reply_form/:message_id', :to => 'landlord_staff_messages#reply_form', as: :landlord_staff_reply_form

  namespace :api do
    namespace :v1 do
      resources :properties, only: :index
    end
  end

  root 'welcome#index'
end

app/views/admins/_document.html.erb
<% @generic_documents.each do |doc| %>
  <% if doc.document_name.present?  %>
    <div class="col-lg-2 col-md-2 col-xl-2 generic-doc mr-2" id="doc-<%=doc.id%>">
      <div class="docs doc-prv" title="<%=doc.document_file%>" data="<%=doc.document_file%>" data-doc-name="<%=doc.document_name.to_s.titleize%>" data-verified="" data-verified-by="">
        <%= document_badge((doc.document_file != '' && !doc.document_file.nil?) ? true : false, 'fas fa-file-pdf', doc.document_name.to_s.titleize) %>
      </div>
      <% expiry = doc.document_expiry ? (doc.document_expiry < Date.today) : false %>
      <% if expiry %>
        <span class="badge badge-danger" title="Document Expiration Date <%= doc.document_expiry.strftime('%d/%m/%Y') %>">Expired</span>
      <% end %>
      <%= link_to edit_generic_document_admin_path(id: doc.id), remote: true, title: 'Edit if expired' do %>
        <i class="fa fa-edit edit-document"></i>
      <% end %>
      <%= link_to destroy_generic_document_admin_path(id: doc.id), method: :delete, remote: true, 'data-confirm': 'Are you sure?', title: 'Delete' do %>
        <i class="fa fa-trash delete-document"></i>
      <% end %>
      <%# <%= link_to "Assign", assign_generic_document_admin_path(id: doc.id), 'data-confirm': 'Are you assign to all properties?', title: 'Assign' %>
    </div>
  <% end %>
<% end %>

app/views/admins/_form_field.html.erb
<div class="row mt-4 new_documents">
  <div class="col-md-4">
    <label> File </label>
    <% if @generic_document.document_file.present? %>
      <br/>
      <%=text_field_tag "document_file[]", @generic_document.document_file.path.split("/").last, id:"label_file_#{@generic_document&.id}", disabled: true, style: 'border: 0; width: 78%', calss: 'from-control' %>
      <%= button_tag :change, type: 'button', id: "change_file_#{ @generic_document&.id}", class: 'btn btn-sm btn-warning' %>
    <% end %>
    <%= file_field_tag 'document_file[]', class: 'form-control', required: @generic_document.document_file.blank?, style: "display: #{@generic_document.document_file.present? ? 'none' : 'block'}", id: "file_#{ @generic_document&.id}" %>
    <%= button_tag :remove_file, type: 'button', id: "remove_file_#{ @generic_document&.id}", class: 'btn btn-sm btn-danger', style: "display: #{(@generic_document.document_file.present? || @generic_document.new_record?) ? 'none' : 'block'}" %>
    <%= hidden_field_tag 'id[]', @generic_document&.id, class: 'form-control'%>
  </div>
  <div class="col-md-3">
    <label> Name </label>
    <%= select_tag 'document_name[]', options_for_select(GenericDocument::GENERIC_DOCUMENT_TYPES.to_a.map(&:reverse)), { class: 'form-control', prompt: 'Select Document', required: true } %>
  </div>
  <div class="col-md-3">
    <label> Expiry Date </label>
    <%= text_field_tag 'document_expiry[]', @generic_document.document_expiry ? @generic_document.document_expiry.strftime('%Y-%m-%d') : Date.today.strftime('%Y-%m-%d'), class: 'form-control date datepicker', 'data-date-format': "yyyy-mm-dd" %>
  </div>
  <div class="col-md-2">
    <br/>
    <%= button_tag 'Cancel', type: 'button', class: 'btn btn-danger remove-document' %>
  </div>
</div>

app/views/admins/_manage_automation_mail_form.html.erb
<div class="modal-header">
  <h3 class="modal-title"><%= @tag.titleize %> Automation Setting</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<%= form_for @manage_automation_mail, url: @url do |f| %>
  <div class="modal-body">
    <div id="automation_error" class="text-danger">
    </div>

    <article>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :mail_type %>
            <%= f.select :mail_type, options_for_select(ManageAutomationMail::AUTOMATION_MAILS, @manage_automation_mail.mail_type), { prompt: 'Select Mail Type' }, class: 'form-control', id: 'mail_types' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :mail_methods %>
            <%= f.select :mail_methods, options_for_select(@options, @manage_automation_mail.mail_methods), { prompt: 'Select Methods' }, class: 'form-control', multiple: true, id: 'mail_methods' %>
          </div>
        </div>
      </div>
    </article>
  </div>
  <div class="modal-footer">
    <%= f.submit "Save", class: 'btn btn-primary'%>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/admins/create_generic_document.js.erb
$('.documents').html("<%= j render 'document'%>");
$('#generic_documents').html('');
$('#generic_document_form')[0].reset();
<% if @errors.present? %>
  $("#notice").show();
  $("#notice").html("<div class='alert alert-danger alert-dismissible fade show'><%= @errors %><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>")
<% else %>
  $("#notice").show();
  $("#notice").html("<div class='alert alert-success alert-dismissible fade show'> <%= @message %><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>")
<% end %>
DocumentPreview();
$('.save-document').hide();
if($('.documents').children('.generic-doc').length >= 4){
  $('.add-generic').hide();
} else {
  $('.add-generic').show();
}

app/views/admins/destroy_generic_document.js.erb
$('.documents').html("<%= j render 'document'%>");
DocumentPreview();
$("#notice").show();
<% if @errors.present? %>
  $("#notice").html("<div class='alert alert-danger alert-dismissible fade show'><%= @error %><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>")
<% else %>
  $("#notice").show();
  $("#notice").html("<div class='alert alert-success alert-dismissible fade show'> <%= @message %><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>")
<% end %>
if($('.documents').children('.generic-doc').length >= 3){
  $('.add-generic').hide();
} else {
  $('.add-generic').show();
}

app/views/admins/edit_generic_document.js.erb
var len = $('#generic_documents').find('.new_documents').length
$('#generic_document_form').attr('action', '/admin/update_generic_document');
// $('#generic_document_form').attr('method', 'patch');
if (parseInt(len) < 4) {
  $('#doc-<%= @generic_document.id %>').hide();
  $('#generic_documents').append("<%= j render 'form_field'%>");
  $(".datepicker").datepicker({ autoclose: true });
  $('.save-document').show();
  $(".remove-document").on('click', function(){
    $(this).parent().parent().remove();
    $('#doc-<%= @generic_document.id %>').show();
    if($('.new_documents').length == 0) {
      $('.save-document').hide();
    } else {
      $('.save-document').show();
    }
  });
  $("#change_file_<%=@generic_document.id%>").on('click', function(){
    console.log('change');
    $("#file_<%= @generic_document&.id%>").show();
    $("#label_file_<%= @generic_document&.id%>").hide();
    $("#remove_file_<%=@generic_document.id%>").show();
    $(this).hide();
  });
  $("#remove_file_<%=@generic_document.id%>").on('click', function(){
    console.log('change');
    $("#file_<%= @generic_document&.id%>").hide();
    $("#label_file_<%= @generic_document&.id%>").show();
    $(this).hide();
    $("#change_file_<%=@generic_document.id%>").show();
  });
  if($('.documents').children().length > 3){
    $('.add-generic').hide();
  }
} else {
  alert('You may only upload four generic documents!')
}
DocumentPreview();
if($('.documents').children('.generic-doc').length >= 3){
  $('.add-generic').hide();
} else {
  $('.add-generic').show();
}

app/views/admins/generic_document.html.erb
<% content_for :title, 'Generic Document' %>
<p id="notice"><%= notice %></p>

<div id="title-bar" class="sticky-top">
  <h1>Generic Document</h1>
  <div class="actions d-flex btn-group justify-content-end push">
    <%= link_to 'Back', admin_path, class: 'ml-2 btn btn-secondary' %>
  </div>
</div>
<article>
  <div id="compliance-docs">
    <div class="col-md-12">
      <%= form_with url: @generic_document.id ? update_generic_document_admin_path : create_generic_document_admin_path, method: 'post', html: { class: 'generic_document_form', id: 'generic_document_form', multipart: true} do |f| %>
        <div class="row">
          <div class="col-md-12 mt-2">
            <%= link_to 'Add general compliance document', new_generic_document_admin_path, remote: true, class: 'add-generic btn btn-primary' %>
          </div>
        </div>
        <div id="generic_documents">
        </div>
        <div class="row mt-4">
          <div class="col-md-12">
            <div class="actions d-flex btn-group justify-content-end push">
              <%= f.submit 'Save', class: 'btn btn-primary save-document'%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row documents">
      <%= render 'document' %>
    </div>
  </div>

</article>

<div class="modal fade" id="doc-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Document: <span class="doc-name"></span></h3> <span class="doc-verified"></span> <span class="doc-verified-by"></span>
        <button type="button" class="close" data-dismiss="modal" style="font-size: 3.5rem !important;"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>
      <div class="modal-body">
        <object data="" type="application/pdf" width="100%" height="520px" class="doc-preview"></object>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  if($('.documents').children('.generic-doc').length >= 4){
    $('.add-generic').hide();
  } else {
    $('.add-generic').show();
  }

</script>

app/views/admins/index.html.erb
<% content_for :title, 'Administration' %>
<div class="page-title">
  <h1>Administartion</h1>
</div>
<article>
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-lg-3 reporting-block">
          <div class="flex-center green-bg">
            <% if Company.exists?(1) %>
              <%= link_to company_path(1), class: 'col-12 box' do %>
                <h2 class="flex-center text-left">
                  <i class="fas fa-mail-bulk"></i>Company details
                </h2>
              <% end %>
            <% else %>
              <%= link_to companies_path, class: 'col-12 box' do %>
                <h2 class="flex-center text-left">
                  <i class="fas fa-mail-bulk"></i>Company details
                </h2>
              <% end %>
            <% end %>

          </div>
        </div>

        <div class="col-lg-3 reporting-block">
          <div class="flex-center deep-grey-bg">
            <%= link_to generic_document_admin_path, class: 'col-12 box' do %>
              <h2 class="flex-center text-left">
                <i class="fas fa-file"></i>Generic Tenancy Documents
              </h2>
            <% end %>
          </div>
        </div>

        <div class="col-lg-3 reporting-block">
          <div class="flex-center flamingo-bg">
            <%= link_to system_signature_admin_path, class: 'col-12 box' do %>
              <h2 class="flex-center text-left">
                <i class="fas fa-file"></i>System Signature
              </h2>
            <% end %>
          </div>
        </div>

        <div class="col-lg-3 reporting-block">
          <div class="flex-center turquoise-bg">
            <%= link_to manage_automation_mail_admin_path, class: 'col-12 box' do %>
              <h2 class="flex-center text-left">
                <i class="fas fa-mail-bulk"></i>Manage Mail Automation
              </h2>
            <% end %>
          </div>
        </div>

<!--        <div class="col-lg-3 reporting-block">-->
<!--          <div class="flex-center green-bg">-->
            <%#= link_to sync_setting_admin_path, class: 'col-12 box' do %>
<!--              <h2 class="flex-center text-left">-->
<!--                <i class="fas fa-cogs"></i>Property Sync-->
<!--              </h2>-->
            <%# end %>
<!--          </div>-->
<!--        </div>-->

        <% if user_signed_in? && current_user.is_admin? %>
          <div class="col-lg-3 reporting-block">
            <div class="flex-center manatee-bg">
              <%= link_to users_path, class: 'col-12 box' do %>
                <h2 class="flex-center text-left">
                  <i class="fas fa-user-tie"></i>User Admin
                </h2>
              <% end %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>

</article>

app/views/admins/manage_automation_mail.html.erb
<% content_for :title, 'Manage Automation Mail' %>
<p id="notice"><%= notice %></p>

<div id="title-bar">
  <h1>Manage Automation Mail</h1>
  <div class="actions d-flex btn-group justify-content-end push">
    <%= link_to 'Back', admin_path, class: 'ml-2 btn btn-secondary' %>
    <%= link_to "Add New", open_automation_mail_admin_path(tag: 'new'), class: "btn btn-primary", remote: "true" %>
  </div>
</div>
<article>
  <div id="automation_mail">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Mail Type</th>
              <th>Mail Methods</th>
              <th>Automation</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @manage_automation_mails.each do |manage_automation_mail| %>
              <tr>
                <td><%= manage_automation_mail.mail_type %></td>
                <td><%= manage_automation_mail.mail_methods.join(', ') %></td>
                <td>
                  <%= check_box_tag :automation, manage_automation_mail.automation, manage_automation_mail.automation, data: {toggle: 'toggle', onstyle: 'success', confirm: 'Are you confirm?', id: manage_automation_mail.id}, class: 'automation' %>
                </td>
                <td>
                  <%= link_to open_automation_mail_admin_path(tag: 'edit', id: manage_automation_mail.id ), remote: true do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to delete_automation_mail_admin_path(id: manage_automation_mail.id), 'data-confirm': 'Are you sure?', method: :delete do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div id="automation">
  </div>
</article>

<%= render 'shared/common_modal' %>

<script type="text/javascript">
  $(document).on('ready turbolinks:load', function() {
    $('.automation').bootstrapToggle();
  });
  $(function() {
    $('.toggle-group').click(function() {
      var $checkbox = $(this).prev('.automation')
      console.log($checkbox.prop('checked'));
      if (confirm("Are you sure you want to do this?")) {
        $.get('/admin/update_manage_automation?id=' + $checkbox.data('id') +'&automation=' + !$checkbox.prop('checked'))
      } else {
        if(!$checkbox.prop('checked')){
          $checkbox.bootstrapToggle('on');
        } else {
          $checkbox.bootstrapToggle('off');
        }
      }
    })
  })
</script>

app/views/admins/new_generic_document.js.erb
var len = $('#generic_documents').find('.new_documents').length + $('.documents').children('.generic-doc').length
$('#generic_document_form').attr('action', '/admin/create_generic_document');
// $('#generic_document_form').attr('method', 'post');
if (parseInt(len) < 4) {
  $('#generic_documents').append("<%= j render 'form_field'%>");
  $(".datepicker").datepicker({ autoclose: true });
  $('.save-document').show();
  $(".remove-document").on('click', function(){
    $(this).parent().parent().remove();
    if($('.new_documents').length == 0) {
      $('.save-document').hide();
    } else {
      $('.save-document').show();
    }
  })
} else {
  alert('You may only upload four generic documents!')
}
DocumentPreview();
if($('.documents').children('.generic-doc').length >= 3){
  $('.add-generic').hide();
} else {
  $('.add-generic').show();
}

app/views/admins/sync_setting.html.erb
<% content_for :title, 'Sync Property' %>
<p id="notice"><%= notice %></p>
<% url = @admin_variable.new_record? ? update_sync_setting_admin_path : update_sync_setting_admin_path(id: @admin_variable) %>
<%= form_for @admin_variable, url: url, method: :patch do |f| %>

  <div id="title-bar">
    <h1>Sync Property</h1>
    <div class="actions d-flex btn-group justify-content-end push">
      <%= link_to 'Back', admin_path, class: 'ml-2 btn btn-secondary mr-2' %>
      <%= f.button 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
  <article>
    <div class="col-md-12">
      <div class="form-group row">
        <%= f.label :rightmove, class:'col-sm-1' %>
        <%= f.check_box :rightmove, class: 'col-sm-1' %>
      </div>
      <div class="form-group row">
        <%= f.label :zoopla, class: 'col-sm-1' %>
        <%= f.check_box :zoopla, class: 'col-sm-1' %>
      </div>
      <div class="form-group row">
        <%= f.label :onthemarket, class: 'col-sm-1' %>
        <%= f.check_box :onthemarket, class: 'col-sm-1' %>
      </div>
    </div>
  </article>
<% end %>

app/views/admins/system_signature.html.erb
<% content_for :title, 'Generic Document' %>
<p id="notice"><%= notice %></p>

<div id="title-bar" class="sticky-top">
  <h1>System Signature</h1>
  <div class="actions d-flex btn-group justify-content-end push">
    <%= link_to 'Back', admin_path, class: 'ml-2 btn btn-secondary' %>
  </div>
</div>
<article>
  <div id="compliance-docs">
    <div class="col-md-12">

    </div>
    <div class="row documents">

    </div>
  </div>

</article>

<div class="modal fade" id="doc-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Document: <span class="doc-name"></span></h3> <span class="doc-verified"></span> <span class="doc-verified-by"></span>
        <button type="button" class="close" data-dismiss="modal" style="font-size: 3.5rem !important;"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>
      <div class="modal-body">
        <object data="" type="application/pdf" width="100%" height="520px" class="doc-preview"></object>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  if($('.documents').children('.generic-doc').length >= 3){
    $('.add-generic').hide();
  } else {
    $('.add-generic').show();
  }

</script>