config/routes.rb
Rails.application.routes.draw do

  resources :companies
  resources :property_utilities
  # get 'tenancy/sign_up'
  concern :attachable do
    resources :attachments, only: :create
  end

  resources :tenancies do
    resources :criminal_records
    resources :additional_tenants
    get :archived
    get :unarchived
    member do
      get :complete
      get :roll_next_year
      get :send_payment_items
      get :tenancy_payment_schedule
    end
  end
  resources :features
  # resources :tenants
  resources :events do
    collection do
      get :reminder
      get :done_reminder
    end
  end
  devise_for :users
  resources :rooms
  resources :listings
  resources :landlords do
    member do
      get :landlord_booking_report
      get :filter_booking_report
      get :send_booking_report
    end
  end
  resources :properties, concerns: [:attachable] do
    collection do
      get :get_properties
      get :get_available_properties
    end
    get :get_rooms
    get :get_filter_rooms
    get :edit_attachment
    patch :update_attachment
    member do
      resource :email_tenants_compliance_documents, only: :create, controller: 'properties/email_tenants_compliance_documents'
      get :resend_statement_report
      get :filter_landlord_statement
      get :filter_annual_landlord_statement
      get :generate_landlord_annual_statement
      get :send_email_to_tenants
    end
    resources :property_expenses, only: %w(new create destroy) do
      collection do
        get :filter_expense
      end
    end
    resources :rooms, only: [:new, :create, :index, :edit, :update] do
      member do
        get :sync
        get :sync_rightmove
        get :sync_zoopla
      end
    end
  end
  delete "remove_property_image/:property_id/:id", :to => "properties#remove_property_image", as: :remove_property_image
  get 'properties/:property_id/set_tenancy_form', to: 'properties#set_tenancy_form', as: :set_tenancy_form
  post 'properties/:property_id/set_tenancy', to: 'properties#set_tenancy', as: :set_tenancy
  get 'tenancies/:tenancy_id/mail_tenancy_dashboard_link', to: 'tenancies#mail_tenancy_dashboard_link', as: :mail_tenancy_dashboard_link

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :messages
  resources :users
  post 'users/create', to: 'users#create', as: :create_new_user
  get 'users/new', to: 'users#new', as: :add_new_user

  get 'events_by_date', to: 'events#events_by_date'
  get 'welcome/index'
  get 'property/units/:status', to: 'welcome#properties', as: :property_units
  get 'calendar/index'

  get 'tenancies/tenancy_dashboard/:u_id', to: 'tenancies#tenancy_dashboard', as: :tenancy_dashboard
  #get 'tenancy/sign_up' #I do not know where to use it :)

  get 'tenancies/booking_form/:u_id', to: 'tenancies#booking_form', as: :booking_form
  post 'tenancies/submit_booking_form/:u_id', to: 'tenancies#submit_booking_form', as: :submit_booking_form

  get 'tenancies/agreement_form/:u_id', to: 'tenancies#agreement_form', as: :agreement_form
  post 'tenancies/submit_agreement_form/:u_id', to: 'tenancies#submit_agreement_form', as: :submit_agreement_form

  get 'tenancies/document_confirmation_form/:u_id', to: 'tenancies#document_confirmation_form', as: :document_confirmation_form
  post 'tenancies/document_confirmation/:u_id', to: 'tenancies#document_confirmation', as: :document_confirmation

  get 'tenancies/final_submission/:u_id', to: 'tenancies#final_submission', as: :submit_tenancy_form

  get 'tenancies/tenancy_dashboard/closed/:u_id', to: 'tenancies#closed_dashboard', as: :closed_dashboard

  get 'guarantors/guarantor_dashboard/:u_id', to: 'guarantors#guarantor_dashboard', as: :guarantor_dashboard

  get 'guarantors/agreement_form/:u_id', to: 'guarantors#agreement_form', as: :guarantor_agreement_form
  post 'guarantors/submit_agreement_form/:u_id', to: 'guarantors#submit_agreement_form', as: :guarantor_submit_agreement_form
  post 'confirm_tenancy_signed/:u_id', to: "guarantors#confirm_tenancy_signed", as: :confirm_signed_tenancy
  get 'guarantors/tenancy_agreement_form/:u_id', to: 'guarantors#tenancy_agreement_form', as: :guarantor_tenancy_agreement_form
  get 'guarantors/complete_guarantor_agreement/:u_id', to: 'guarantors#complete_guarantor_agreement', as: :complete_guarantor_agreement
  get 'mail_guarantor_dashboard_link', to: "guarantors#mail_guarantor_dashboard_link", as: :mail_guarantor_dashboard_link

  get 'reporting/index'
  get 'reporting/compliance_documents', to: 'reporting#compliance_documents', as: :reporting_compliance_documents
  get 'reporting/list_of_people_in_arrears', :to => 'reporting#list_of_people_in_arrears', as: :list_of_people_in_arrears
  get 'reporting/viewings', :to => 'reporting#viewings', as: :viewings
  get 'reporting/property_listings', :to => 'reporting#property_listings', as: :property_listings
  get 'reporting/tenancies', to: 'reporting#tenancies', as: :reporting_tenancies
  get 'reporting/combined_landlord_report', to: 'reporting#combined_landlord_report', as: :reporting_combined_landlord
  get "/print", to: "reporting#print_arrears", as: :print_arrears_report
  get "/send-arrear-report", to: "reporting#send_arrear_report", as: :send_arrear_report
  # get "/monthly-reports", to: "reporting#monthly_statement_report", as: :monthly_statement_reports
  # get "/send-property-report", to: "reporting#send_property_report", as: :send_property_report
  get "/set_custom_report_date", to: "reporting#set_custom_report_date", as: :set_custom_report_date
  get "/print-compliance-document", to: "reporting#print_compliance_report", as: :print_compliance_report
  get "/annual-commission-report", to: "reporting#annual_commission_report", as: :annual_commission_report
  get "/annual-rent-report", to: "reporting#annual_rent_report", as: :annual_rent_report
  get "/print-annual-rent-report", to: "reporting#print_annual_rent_report", as: :print_annual_rent_report
  get "/print-commission-income-report", to: "reporting#print_annual_commission_report", as: :print_annual_commission_report
  get "/sales-analysis-report", to: "reporting#sales_analysis_report", as: :sales_analysis_report
  get "/availability", to: "reporting#available_room", as: :available_room
  get "/print-availability", to: "reporting#print_available_room", as: :print_available_room
  get "/filter_sales_analysis_report", to: "reporting#filter_sales_analysis_report", as: :filter_sales_analysis_report
  get "print-sales-analysis-report", to: "reporting#print_sales_analysis_report", as: :print_sales_analysis_report
  get 'tenancy_payment_item_form/:tenancy_id', :to => 'tenancies#tenancy_payment_item_form', as: :tenancy_payment_item_form
  get "/monthly-payment-report", to: "reporting#monthly_payment_report", as: :monthly_payment_report
  get "/print-monthly-payment-report", to: "reporting#print_monthly_payment_report", as: :print_monthly_payment_report
  get "generate-monthly-payment-report",  to: "reporting#generate_monthly_payment_report", as: :generate_monthly_payment_report
  post 'tenancy_payment_item/:tenancy_id', :to => 'tenancies#tenancy_payment_item', as: :tenancy_payment_item
  delete 'tenancy_payment_item_delete/:item_id', :to => 'tenancies#tenancy_payment_item_delete', as: :tenancy_payment_item_delete
  resources :errors

  get 'filter_rooms', :to => 'rooms#filter_rooms', as: :filter_rooms

  resources :tenancy_staff_conversations, only: [:index, :new, :create] do
    resources :tenancy_staff_messages, only: [:index, :new, :create]
  end
  resources :tenancy_staff_messages

  ## admin section
  resource :admin, only: [] do
    get '/', to: 'admins#index'
    get '/generic-document', to: 'admins#generic_document'
    get '/system-signature', to: 'admins#system_signature'
    get :new_generic_document
    post :create_generic_document
    get :edit_generic_document
    delete :destroy_generic_document
    post :update_generic_document
    get :assign_generic_document
    get '/manage-automation-mail', to:'admins#manage_automation_mail'
    post :create_manage_automation_mail
    patch '/admin/update_manage_automation_mail/:id', to:'admins#update_manage_automation_mail', as: :update_manage_automation_mail
    get :open_automation_mail
    get :get_mail_options
    get :edit_automation_mail
    get :update_manage_automation
    get :sync_setting
    patch :update_sync_setting
    delete :delete_automation_mail
  end

  get 'tenancy_staff_messages/reply_form/:message_id', :to => 'tenancy_staff_messages#reply_form', as: :tenancy_staff_reply_form

  resources :landlord_staff_conversations, only: [:index, :new, :create] do
    resources :landlord_staff_messages, only: [:index, :new, :create]
  end
  resources :landlord_staff_messages

  get 'landlord_staff_messages/reply_form/:message_id', :to => 'landlord_staff_messages#reply_form', as: :landlord_staff_reply_form

  namespace :api do
    namespace :v1 do
      resources :properties, only: :index
    end
  end

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    today = Date.today
    @year = @current_year
    @selected_date          = params[:selected_date] if params[:selected_date].present?
    @properties             = Property.all
    @rooms                  = Room.all
    # @rooms_let              = Room.where(let_status: 1) # Not in use
    # @rooms_not_let          = Room.where(let_status: 0) # Not in use
    @events                 = Event.all
    @viewings               = Event.where(event_type: 1)
    @maintenance            = Event.where(event_type: 2)
    @holidays               = Event.where(event_type: 4)
    @landlords              = Landlord.all
    @users                  = User.all
    @user_events            = Event.joins(:event_users).where(event_users: {user_id: current_user.id}).where(events: {start: Date.today.all_day}).order(:start)
    @today_events           = Event.where("DATE(events.start) = ?", Date.today.strftime)
    @week_events            = Event.where("DATE(events.start) >= ? AND DATE(events.end) <= ?", Date.today.beginning_of_week.strftime, Date.today.end_of_week.strftime)
    @month_events           = Event.where("DATE(events.start) >= ? AND DATE(events.end) <= ?", Date.today.beginning_of_month.strftime, Date.today.end_of_month.strftime)
    @tenancies              = Tenancy.all
    @unsigned_booking_form  = @tenancies.where(form_submitted: 0)
    @unsigned_agreement     = @tenancies.where(signed_tenancy_agreement: 0)
    @today_events_for_non_admin_users = Event.order(:start).today_events_for_non_admin_users
    @room_tenancies = @rooms.joins(:tenancies)
    @booked_rooms = @room_tenancies.where('tenancies.booking_status = ?', 1).count
    @completed_rooms = @room_tenancies.where('tenancies.booking_status = ?', 2).count
    @available_rooms = @rooms.where(availability: true).count
    @next_month_expire_tenancies = @tenancies.where("tenancy_end BETWEEN ? AND ?", Time.now, Time.now + 30.days).count
    @next_month_expire_documents = ComplianceDocument.where('extract(month from document_expiry) = ? AND extract(year from document_expiry) = ?', (Time.now + 1.month).strftime('%m'), (Time.now + 1.month).strftime('%Y')).count
    @properties_listed = Property.where('list_on_3rd_party_websites = true').count
  end

  def properties
    rooms = Room.joins(:property)
    tenancy_rooms = rooms.joins(:tenancies)
    @status = params[:status]
    year = params[:year] ? params[:year] : @current_year
    notice_rooms = tenancy_rooms.where("tenancies.year = ? and tenancies.booking_status = ?", year, 3)
    complete_rooms = tenancy_rooms.where("tenancies.year = ? and tenancies.booking_status = ?", year, 2)
    booking_rooms = tenancy_rooms.where("tenancies.year = ? and tenancies.booking_status = ?", year, 1)
    ids = complete_rooms.ids + booking_rooms.ids
    available_rooms = rooms.where.not(id: ids)
    # @rooms = @status == 'available' ? available_rooms : @status == 'booking' ? booking_rooms : complete_rooms
    case @status
      when 'available'
        @rooms = available_rooms
        @notice_rooms = notice_rooms
      when 'booking'
        @rooms = booking_rooms
      when 'complete'
        @rooms = complete_rooms
      when 'notice'
        @rooms = notice_rooms
      else
    end

    @booking_tenancies = Tenancy.where(room_id: @rooms.ids, year: year, booking_status: 1).group_by(&:room_id) if @status == 'booking'

    if @status == 'booking'
      @rooms = @rooms.order('tenancies.dashboard_link_mail_at, properties.street, properties.id, rooms.number').uniq
    elsif @status == 'available'
      @rooms = @rooms.order('properties.street, properties.id, rooms.number').uniq
      @notice_rooms = @notice_rooms.order('properties.street, properties.id, rooms.number').uniq
    else
      @rooms = @rooms.order('properties.street, properties.id, rooms.number').uniq
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def details event
    content_tag(:div, class: 'row') do
      content_tag(:div, class: 'col-2') do
        event.start.strftime("%H:%M")
      end +
      content_tag(:div, class: 'col-5') do
        event.client_name
      end +
      content_tag(:div, class: 'col-5') do
        event.client_contact_number
      end
    end
  end

  def status_title status
    case status
    when 'available'
      "Properties Available"
    when 'booking'
      "Properties Under Booking"
    when 'complete'
      "Complete Properties"
    when "notice"
      "Properties Given Notice"
    else
      "#{status} undefined"
    end
  end
end

app/views/welcome/index.html.erb
<% content_for :title, 'DataManager dashboard' %>
<div class="page-title" style="flex-direction: row; display: flex">
  <h1><%= current_user.first_name %>'s dashboard</h1>
  <div class="" style="display: flex; margin-left: auto">
    <h4 style="padding: 6px;"><b>Year:</b></h4>
    <div id="business-years">
      <% business_years(false).each_with_index do |year, i| %>
        <span class="badge <%= @current_year == year ? 'badge-primary' : "badge-secondary btn-#{i}" %> filter-available-rooms" data-date="<%= year %>"><%= year %></span>
      <% end %>
    </div>
  </div>
</div>
<div id="dashboard">
  <div class="row">
    <div id="home-left" class="col-md-12 col-lg-6">
      <div class="row">
        <div class="col-md-12">
          <div id="my-day" class="dashboard-block">
            <div class="row">
              <div class="col-10 col-lg-9">
                <%= link_to calendar_index_path do %>
                  <h2><i class="fas fa-calendar"></i><span class="hide-b-lg"><%= agent? ? 'My Day' : 'Team Day' %> - </span> <%= Date.today.strftime("%A %d %B") %></h2>
                <% end %>
              </div>
              <div class="col-2 col-lg-3 d-flex justify-content-center">
                <%= link_to '<i class="fas fa-calendar-week"></i>'.html_safe, calendar_index_path, class: 'view-cal d-lg-none' %>
                <%= link_to 'View Calendar', calendar_index_path, class: 'view-cal d-none d-lg-block' %>
              </div>
            </div>
            <div class="row header-row">
              <div class="col-2">Time</div>
              <div class="col-5">With</div>
              <div class="col-5">Mobile</div>
            </div>
<!--            <div class="parent" style="display: flex;height:300px;">-->
              <ul id="my-events">
                <% if agent? %>
                  user
                  <% @user_events.each do |event| %>
                    <li>
                      <%= link_to details(event), event %>
                    </li>
                  <% end %>
                <% else %>
                  <% @today_events_for_non_admin_users.each do |event| %>
                    <li>
                      <%= link_to details(event), event %>
                    </li>
                  <% end %>
                <% end %>
              </ul>
<!--            </div>-->
            <table id="viewings" class="table">
              <tbody>
                <tr>
                  <td><%= link_to 'Today viewings', viewings_path(timing: 'today_events'), style: 'color: #ffff;' %></td>
                  <td><%= @today_events.count rescue 0 %></td>
                  <td><%= link_to 'This week viewings', viewings_path(timing: 'week_events'), style: 'color: #ffff;' %></td>
                  <td><%= @week_events.count rescue 0 %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div id="home-right" class="col-md-12 col-lg-6">
      <div class="row">
        <div class="col-md-12">
          <div id="property" class="dashboard-block square">
            <%= link_to properties_path do %>
              <h2><i class="fas fa-home"></i>Properties</h2>
            <% end %>
            <div class="table-responsive">
              <table class="table">
                <tbody>
                  <tr>
                    <td><strong>Total Units</strong></td>
                    <td><strong><%= @rooms.count %></strong></td>
                  </tr>
                  <tr class="data">
                    <td colspan="2" style="padding: 7px 0;">
                      <div class="d-none d-lg-block">
                        <div class="top_row">
                          <div><%= link_to 'Available', property_units_path(status: 'available', year: @current_year), class: 'room_status' %></div>
                          <div><%= link_to 'Booking', property_units_path(status: 'booking', year: @current_year), class: 'room_status' %></div>
                          <div><%= link_to 'Completed', property_units_path(status: 'complete', year: @current_year), class: 'room_status' %></div>
                          <div><%= link_to 'Notice', property_units_path(status: 'notice', year: @current_year), class: 'room_status' %></div>
                        </div>
                        <div class="top_row">
                          <% filtered_rooms = filter_room(@current_year) %>
                          <div class="no-of-available-rooms"><%= filtered_rooms[:available_rooms] %></div>
                          <div class="rooms-under-booking"><%= filtered_rooms[:rooms_under_booking]%></div>
                          <div class="no-of-booked-rooms"><%= filtered_rooms[:booked_rooms]%></div>
                          <div class="no-of-notice-rooms"><%= filtered_rooms[:notice_rooms]%></div>
                        </div>
                      </div>
                      <div class="d-lg-none">
                        <div class="row unit-mobile-row">
                          <div class="col-6 text-left">
                            <%= link_to 'Available', property_units_path(status: 'available', year: @current_year), class: 'room_status' %>
                          </div>
                          <div class="col-6">
                            <%= filtered_rooms[:available_rooms] %>
                          </div>
                        </div>
                        <div class="row unit-mobile-row">
                          <div class="col-6 text-left">
                            <%= link_to 'Booking', property_units_path(status: 'booking', year: @current_year), class: 'room_status' %>
                          </div>
                          <div class="col-6">
                            <%= filtered_rooms[:rooms_under_booking]%>
                          </div>
                        </div>
                        <div class="row unit-mobile-row">
                          <div class="col-6 text-left">
                            <%= link_to 'Completed', property_units_path(status: 'complete', year: @current_year), class: 'room_status' %>
                          </div>
                          <div class="col-6">
                            <%= filtered_rooms[:booked_rooms]%>
                          </div>
                        </div>
                        <div class="row unit-mobile-row">
                          <div class="col-6 text-left">
                            <%= link_to 'Notice', property_units_path(status: 'notice', year: @current_year), class: 'room_status' %>
                          </div>
                          <div class="col-6">
                            <%= filtered_rooms[:notice_rooms]%>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <%= link_to property_listings_path, class: 'marketed-link' do %>
              <h3><i class="fas fa-bullhorn"></i> Marketed <%= @properties_listed %></h3>
            <% end %>
          </div>
        </div>
<!--        <div class="col-md-6">-->
<!--          <div id="finance" class="dashboard-block square">-->
            <%#= link_to list_of_people_in_arrears_path do %>
<!--              <h2><i class="fas fa-chart-line"></i>Arrears</h2>-->
            <%# end %>
<!--            <table class="table">-->
<!--              <tbody>-->
<!--              <tr>-->
<!--                <td>-->
                  <%#= link_to 'No. people in arrears', list_of_people_in_arrears_path, style: 'color: #ffff;' %>
<!--                </td>-->
<!--                <td><%#= TenancyPaymentItem.number_of_people_in_arrears_today.pluck(:tenancy_id).uniq.count %></td>-->
<!--              </tr>-->
<!--              <tr>-->
<!--                <td>Total arrears value</td>-->
                <!-- <td>&#163;<%#= number_with_delimiter(sprintf("%.2f",TenancyPaymentItem.number_of_people_in_arrears_today.pluck(:amount_due).inject(0){|sum,x| sum + x }, :delimiter => ',') %></td> -->
<!--                <td>&#163;<%#= number_with_delimiter(sprintf("%.2f",TenancyPaymentItem.number_of_people_in_arrears_today.where(-->
<!--                  due_date: Date.parse("01-09-20#{@year.split('/')[0]}")..Date.parse("31-08-20#{@year.split('/')[1]}")-->
<!--                ).pluck(:arrears).sum(&:to_f)), :delimiter => ',') %></td>-->
<!--              </tr>-->
<!--              </tbody>-->
<!--            </table>-->
<!--          </div>-->
<!--        </div>-->
        <div class="col-lg-6">
          <div id="documents-outstanding" class="dashboard-block square">
            <%= link_to reporting_tenancies_path do %>
              <h2><i class="fas fa-file"></i>Expiring</h2>
            <% end %>
            <table class="table">
              <tbody>
                <tr>
                  <td><%= link_to "Tenancies", reporting_tenancies_path, style: 'color: #ffff;' %></td>
                  <td><%= @next_month_expire_tenancies %></td>
                </tr>
                <tr>
                  <td><%= link_to 'Certifications', reporting_compliance_documents_path(anchor: 'next_month_expired'),  style: 'color: #ffff;' %></td>
                  <td><%= @next_month_expire_documents %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-md-6">
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.filter-available-rooms').on('click', function(){
      $(".filter-available-rooms").removeClass("badge-primary");
      $(".filter-available-rooms").addClass("badge-secondary");
      $(this).removeClass("badge-secondary");
      $(this).addClass("badge-primary");
      var years_range = $(this).data("date");
      $('.room_status').each(function(){
        var url = $(this).attr('href').split('=');
        $(this).attr('href', url[0] + '=' + years_range);
      })
      $.ajax({
        url: '/filter_rooms',
        type: "GET",
        data: {year: years_range, return_object: false},
        dataType: 'json',
        success: function (data) {
          $('.no-of-available-rooms').replaceWith('<div class="no-of-available-rooms">'+data['available_rooms']+'</div>');
          $('.no-of-booked-rooms').replaceWith('<div class="no-of-booked-rooms">'+data['booked_rooms']+'</td>');
          $('.rooms-under-booking').replaceWith('<div class="rooms-under-booking">'+data['rooms_under_booking']+'</div>');
        },
        error: function (data) {

        }
      });
    });
  });
</script>

app/views/welcome/properties.html.erb
<% content_for :title, 'Availability Report' %>
<p id="notice"><%= notice %></p>
<div id="title-bar" class="sticky-top">
  <h1><%= @status.to_s.titleize %> Properties</h1>
  <div class="actions d-flex btn-group justify-content-end push">
    <%= link_to 'Back', welcome_index_path, class: 'btn btn-secondary' %>
  </div>
</div>

<article>
  <section>
    <h3 class="article-title">Key Figures</h3>
    <div class="row">
      <div class="col-sm-4">
        <h3><%= status_title(@status) %></h3>
        <div class="key-section">
          <%= @rooms.count %>
        </div>
      </div>
    </div>
  </section>
  <section>
    <h3 class="article-title"><%= @status.to_s.titleize %> Rooms</h3>
    <div class="col-md-12 mt-2">
      <div class="row">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <th>Address</th>
              <th>Room</th>
              <th>Rate</th>
              <% if @status == 'booking' && @booking_tenancies.count > 0 %>
                <th class="">Tenancy Name</th>
                <th class="">Sent</th>
                <th class="tenancy-header t_icon"><i class="fas fa-edit" title="Booking form completed"></i></th>
                <th class="tenancy-header t_icon"><i class="fas fa-signature" title="Signed Tenancy"></i></th>
                <th class="tenancy-header t_icon"><i class="fas fa-user-lock" title="Guarantor"></i></th>
                <th title="Advanced Rent / Deposit Paid">AvR/DPT</th>
                <% end %>
            </thead>
            <tbody>
              <% @rooms.each do |room| %>
                <tr class="<%= @status %>">
                  <td><%= link_to room&.property&.property_name, property_path(room.property) %></td>
                  <td><%= room.number %></td>
                  <td>£<%= number_with_delimiter(sprintf("%.2f",room.list_price.to_f), delimiter: ',') %></td>
                  <% if @status == 'booking' && @booking_tenancies.count > 0 %>
                    <% @booking_tenancies[room.id].each do |tenancy| %>
                        <td class="link_sub_tenancy"><%= link_to tenancy.tenant_name, tenancy_path(tenancy.id) %></td>
                        <td class="t_icon"><%= tenancy.dashboard_link_mail_at.try(:strftime, '%d/%m/%Y') %></td>
<!--                        <td class="t_icon"><%#= l(tenancy.dashboard_link_mail_at, format: :nice, default: '') %></td>-->
                        <td class="t_icon"><%= yes_no(tenancy.form_submitted) %></td>
                        <td class="t_icon"><%= yes_no(tenancy.signed_tenancy_agreement) %></td>
                        <td class="t_icon">
                          <% if tenancy.is_guarantor_available == true %>
                            <%= yes_no(tenancy&.guarantor&.complete_guarantor_agreement) %>
                          <% else %>
                            <i class="fas fa-times-circle" style="color: red"></i>
                          <% end %>
                        </td>
                        <td class="t_icon"><%= avr_dpt_display(tenancy) %></td>
                    <% end if @booking_tenancies[room.id].present? %>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </section>

  <% if @status == 'available' %>
    <section>
      <h3 class="article-title">Notice Rooms</h3>
      <div class="col-md-12 mt-2">
        <div class="row">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <th>Address</th>
                <th>Room</th>
                <th>Rate</th>
              </thead>
              <tbody>
              <% @notice_rooms.each do |room| %>
                <tr class="<%= @status %>">
                  <td><%= link_to room&.property&.property_name, property_path(room.property) %></td>
                  <td><%= room.number %></td>
                  <td>£<%= number_with_delimiter(sprintf("%.2f",room.list_price.to_f), delimiter: ',') %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</article>