config/routes.rb
Rails.application.routes.draw do

  resources :companies
  resources :property_utilities
  # get 'tenancy/sign_up'
  concern :attachable do
    resources :attachments, only: :create
  end

  resources :tenancies do
    resources :criminal_records
    resources :additional_tenants
    get :archived
    get :unarchived
    member do
      get :complete
      get :roll_next_year
      get :send_payment_items
      get :tenancy_payment_schedule
    end
  end
  resources :features
  # resources :tenants
  resources :events do
    collection do
      get :reminder
      get :done_reminder
    end
  end
  devise_for :users
  resources :rooms
  resources :listings
  resources :landlords do
    member do
      get :landlord_booking_report
      get :filter_booking_report
      get :send_booking_report
    end
  end
  resources :properties, concerns: [:attachable] do
    collection do
      get :get_properties
      get :get_available_properties
    end
    get :get_rooms
    get :get_filter_rooms
    get :edit_attachment
    patch :update_attachment
    member do
      resource :email_tenants_compliance_documents, only: :create, controller: 'properties/email_tenants_compliance_documents'
      get :resend_statement_report
      get :filter_landlord_statement
      get :filter_annual_landlord_statement
      get :generate_landlord_annual_statement
      get :send_email_to_tenants
    end
    resources :property_expenses, only: %w(new create destroy) do
      collection do
        get :filter_expense
      end
    end
    resources :rooms, only: [:new, :create, :index, :edit, :update] do
      member do
        get :sync
        get :sync_rightmove
        get :sync_zoopla
      end
    end
  end
  delete "remove_property_image/:property_id/:id", :to => "properties#remove_property_image", as: :remove_property_image
  get 'properties/:property_id/set_tenancy_form', to: 'properties#set_tenancy_form', as: :set_tenancy_form
  post 'properties/:property_id/set_tenancy', to: 'properties#set_tenancy', as: :set_tenancy
  get 'tenancies/:tenancy_id/mail_tenancy_dashboard_link', to: 'tenancies#mail_tenancy_dashboard_link', as: :mail_tenancy_dashboard_link

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :messages
  resources :users
  post 'users/create', to: 'users#create', as: :create_new_user
  get 'users/new', to: 'users#new', as: :add_new_user

  get 'events_by_date', to: 'events#events_by_date'
  get 'welcome/index'
  get 'property/units/:status', to: 'welcome#properties', as: :property_units
  get 'calendar/index'

  get 'tenancies/tenancy_dashboard/:u_id', to: 'tenancies#tenancy_dashboard', as: :tenancy_dashboard
  #get 'tenancy/sign_up' #I do not know where to use it :)

  get 'tenancies/booking_form/:u_id', to: 'tenancies#booking_form', as: :booking_form
  post 'tenancies/submit_booking_form/:u_id', to: 'tenancies#submit_booking_form', as: :submit_booking_form

  get 'tenancies/agreement_form/:u_id', to: 'tenancies#agreement_form', as: :agreement_form
  post 'tenancies/submit_agreement_form/:u_id', to: 'tenancies#submit_agreement_form', as: :submit_agreement_form

  get 'tenancies/document_confirmation_form/:u_id', to: 'tenancies#document_confirmation_form', as: :document_confirmation_form
  post 'tenancies/document_confirmation/:u_id', to: 'tenancies#document_confirmation', as: :document_confirmation

  get 'tenancies/final_submission/:u_id', to: 'tenancies#final_submission', as: :submit_tenancy_form

  get 'tenancies/tenancy_dashboard/closed/:u_id', to: 'tenancies#closed_dashboard', as: :closed_dashboard

  get 'guarantors/guarantor_dashboard/:u_id', to: 'guarantors#guarantor_dashboard', as: :guarantor_dashboard

  get 'guarantors/agreement_form/:u_id', to: 'guarantors#agreement_form', as: :guarantor_agreement_form
  post 'guarantors/submit_agreement_form/:u_id', to: 'guarantors#submit_agreement_form', as: :guarantor_submit_agreement_form
  post 'confirm_tenancy_signed/:u_id', to: "guarantors#confirm_tenancy_signed", as: :confirm_signed_tenancy
  get 'guarantors/tenancy_agreement_form/:u_id', to: 'guarantors#tenancy_agreement_form', as: :guarantor_tenancy_agreement_form
  get 'guarantors/complete_guarantor_agreement/:u_id', to: 'guarantors#complete_guarantor_agreement', as: :complete_guarantor_agreement
  get 'mail_guarantor_dashboard_link', to: "guarantors#mail_guarantor_dashboard_link", as: :mail_guarantor_dashboard_link

  get 'reporting/index'
  get 'reporting/compliance_documents', to: 'reporting#compliance_documents', as: :reporting_compliance_documents
  get 'reporting/list_of_people_in_arrears', :to => 'reporting#list_of_people_in_arrears', as: :list_of_people_in_arrears
  get 'reporting/viewings', :to => 'reporting#viewings', as: :viewings
  get 'reporting/property_listings', :to => 'reporting#property_listings', as: :property_listings
  get 'reporting/tenancies', to: 'reporting#tenancies', as: :reporting_tenancies
  get 'reporting/combined_landlord_report', to: 'reporting#combined_landlord_report', as: :reporting_combined_landlord
  get "/print", to: "reporting#print_arrears", as: :print_arrears_report
  get "/send-arrear-report", to: "reporting#send_arrear_report", as: :send_arrear_report
  # get "/monthly-reports", to: "reporting#monthly_statement_report", as: :monthly_statement_reports
  # get "/send-property-report", to: "reporting#send_property_report", as: :send_property_report
  get "/set_custom_report_date", to: "reporting#set_custom_report_date", as: :set_custom_report_date
  get "/print-compliance-document", to: "reporting#print_compliance_report", as: :print_compliance_report
  get "/annual-commission-report", to: "reporting#annual_commission_report", as: :annual_commission_report
  get "/annual-rent-report", to: "reporting#annual_rent_report", as: :annual_rent_report
  get "/print-annual-rent-report", to: "reporting#print_annual_rent_report", as: :print_annual_rent_report
  get "/print-commission-income-report", to: "reporting#print_annual_commission_report", as: :print_annual_commission_report
  get "/sales-analysis-report", to: "reporting#sales_analysis_report", as: :sales_analysis_report
  get "/availability", to: "reporting#available_room", as: :available_room
  get "/print-availability", to: "reporting#print_available_room", as: :print_available_room
  get "/filter_sales_analysis_report", to: "reporting#filter_sales_analysis_report", as: :filter_sales_analysis_report
  get "print-sales-analysis-report", to: "reporting#print_sales_analysis_report", as: :print_sales_analysis_report
  get 'tenancy_payment_item_form/:tenancy_id', :to => 'tenancies#tenancy_payment_item_form', as: :tenancy_payment_item_form
  get "/monthly-payment-report", to: "reporting#monthly_payment_report", as: :monthly_payment_report
  get "/print-monthly-payment-report", to: "reporting#print_monthly_payment_report", as: :print_monthly_payment_report
  get "generate-monthly-payment-report",  to: "reporting#generate_monthly_payment_report", as: :generate_monthly_payment_report
  post 'tenancy_payment_item/:tenancy_id', :to => 'tenancies#tenancy_payment_item', as: :tenancy_payment_item
  delete 'tenancy_payment_item_delete/:item_id', :to => 'tenancies#tenancy_payment_item_delete', as: :tenancy_payment_item_delete
  resources :errors

  get 'filter_rooms', :to => 'rooms#filter_rooms', as: :filter_rooms

  resources :tenancy_staff_conversations, only: [:index, :new, :create] do
    resources :tenancy_staff_messages, only: [:index, :new, :create]
  end
  resources :tenancy_staff_messages

  ## admin section
  resource :admin, only: [] do
    get '/', to: 'admins#index'
    get '/generic-document', to: 'admins#generic_document'
    get '/system-signature', to: 'admins#system_signature'
    get :new_generic_document
    post :create_generic_document
    get :edit_generic_document
    delete :destroy_generic_document
    post :update_generic_document
    get :assign_generic_document
    get '/manage-automation-mail', to:'admins#manage_automation_mail'
    post :create_manage_automation_mail
    patch '/admin/update_manage_automation_mail/:id', to:'admins#update_manage_automation_mail', as: :update_manage_automation_mail
    get :open_automation_mail
    get :get_mail_options
    get :edit_automation_mail
    get :update_manage_automation
    get :sync_setting
    patch :update_sync_setting
    delete :delete_automation_mail
  end

  get 'tenancy_staff_messages/reply_form/:message_id', :to => 'tenancy_staff_messages#reply_form', as: :tenancy_staff_reply_form

  resources :landlord_staff_conversations, only: [:index, :new, :create] do
    resources :landlord_staff_messages, only: [:index, :new, :create]
  end
  resources :landlord_staff_messages

  get 'landlord_staff_messages/reply_form/:message_id', :to => 'landlord_staff_messages#reply_form', as: :landlord_staff_reply_form

  namespace :api do
    namespace :v1 do
      resources :properties, only: :index
    end
  end

  root 'welcome#index'
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def has_tenant(room)
    #user.email if user && user.email.present?
    room.tenancy.find_by(room_id: room.id).tenant_full_name
  end

  def check_room_availability(room)
    property_rooms = room.property.rooms.count
    available_rooms = room.property.rooms.available.count
    div = ''
    if property_rooms == available_rooms
      div = '<div class="available col-1 bg-success">'+available_rooms.to_s+'</div>'
    elsif available_rooms<property_rooms && available_rooms != 0
      div = '<div class="available col-1 bg-warning">'+available_rooms.to_s+'</div>'
    else
      div = '<div class="available col-1 bg-danger">'+available_rooms.to_s+'</div>'
    end
    return div
  end

  def check_property_availability(property)
    pr_rooms = property.rooms.eager_load(:tenancies)
    pr_room_count = pr_rooms.count
    tenancy_rooms = Tenancy.where(booking_status: 2).pluck(:room_id).uniq
    property_room_count = pr_rooms.where.not(id: tenancy_rooms).count
    currently_occupied = pr_rooms.where('tenancies.booking_status = ?', 2).count

    div = ''
    class_name = (pr_room_count > 0 && property_room_count == pr_room_count) ? 'bg-success' : currently_occupied >= 1 ? 'bg-warning' : 'bg-danger'
    div = "<div class='available #{class_name}'>"+property_room_count.to_s+'</div>'
    return div
  end

  def property_available(property, type = "available_ratio")
    rooms = property.rooms
    property_total_rooms = rooms.count
    property_available_rooms = rooms.where(availability: true).count
    property_currently_occupied_rooms = rooms.where(availability: false).count
    value = ''
    if type == "class"
      if property_currently_occupied_rooms == 0
        value = 'available'
      elsif property_currently_occupied_rooms > 0
        value = 'partially-available'
      elsif property_available_rooms == 0
        value = 'booked'
      end
    else
      if property_currently_occupied_rooms == 0
        value = property_available_rooms.to_s+"/"+property_total_rooms.to_s+' ( '+' <span style="color: #3a7e37;"> Available</span> )'
      elsif property_currently_occupied_rooms > 0
        avl_txt = property_available_rooms > 1 ? property_available_rooms.to_s+' rooms' : property_available_rooms.to_s+' room'
        value = property_available_rooms.to_s+"/"+property_total_rooms.to_s+' ( '+ ' <span style="color: #de9040;"> '+avl_txt+' left</span> )'
      elsif property_available_rooms == 0
        value = property_available_rooms.to_s+"/"+property_total_rooms.to_s+' ( '+' <span style="color: #dc4545;"> Fully booked</span> )'
      end
    end
    return value
  end

  def property_num_available(property)
    rooms = property.rooms
    property_total_rooms = rooms.count
    property_available_rooms = rooms.where(availability: true).count
    property_currently_occupied_rooms = rooms.where(availability: false).count
    value = ''

    if property_currently_occupied_rooms == 0
      value = property_available_rooms.to_s+"/"+property_total_rooms.to_s
    elsif property_currently_occupied_rooms > 0
      avl_txt = property_available_rooms > 1 ? property_available_rooms.to_s+' rooms' : property_available_rooms.to_s+' room'
      value = property_available_rooms.to_s+"/"+property_total_rooms.to_s
    elsif property_available_rooms == 0
      value = property_available_rooms.to_s+"/"+property_total_rooms.to_s
    end

    return value
  end

  def filter_room(year)
    rooms = Room.all
    tenancy_rooms = rooms.joins(:tenancies)
    notice_rooms = tenancy_rooms.where("tenancies.year = ? and tenancies.booking_status = ?", year, 3)
    total_complete_rooms_for_the_year = tenancy_rooms.where("tenancies.year = ? and tenancies.booking_status = ?", year, 2)
    rooms_under_booking = tenancy_rooms.where("tenancies.year = ? and tenancies.booking_status = ?", year, 1)
    ids = total_complete_rooms_for_the_year.ids + rooms_under_booking.ids
    available_rooms = rooms.where.not(id: ids)
    if (params[:return_object].present? && params[:return_object])
      available_rooms = available_rooms
    end
    total_complete_rooms_for_the_year = total_complete_rooms_for_the_year
    if (params[:return_object].present? && params[:return_object])
      total_complete_rooms_for_the_year = total_complete_rooms_for_the_year
    end


    return {
      notice_rooms: notice_rooms.uniq.count,
      booked_rooms: total_complete_rooms_for_the_year.uniq.count,
      available_rooms: available_rooms.uniq.count,
      rooms_under_booking: rooms_under_booking.uniq.count
    }
  end
end

app/views/rooms/_form.html.erb
<%= simple_form_for([@property, @room], html: { class: '' }) do |f| %>
  <div id="title-bar" class="sticky-top">
    <h1><%=raw @room.number.present? ? "#{@room.property.property_name}"+'-'+"#{@room.number+"<small class='edit'>- Edit mode</small>".html_safe}" : "#{@property.property_name}"+'-'+"New Room" %> </h1>
    <div class="actions d-flex justify-content-end push">
      <% if current_user.admin? %>
        <%= link_to (fa_icon 'trash'), @room, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger del' unless @room.new_record? %>
      <% end %>
      <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
      <%= f.submit (@room.new_record? ? 'Create New Room' : 'Update Room'), class: 'btn btn-success' %>
    </div>
  </div>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <article>
    <section>
      <h3 class="article-title">Room Details</h3>
      <div class="form-group">
        <%= f.label :number, 'Room No. / Name' %>
        <%= f.text_field :number, id: :room_number, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, id: :room_description, class: 'form-control', rows: 6 %>
      </div>

      <div class="form-group">
        <%= f.input :dimensions, class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col">
            <%= f.label :list_price %>
            <%= f.text_field :list_price, id: :room_list_price, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :ensuite %>
        <%= f.input_field :ensuite, as: :boolean %>
      </div>
      <!--    <div class="form-group">-->
      <%#= f.label :availability %>
      <%#= f.input_field :availability, as: :boolean %>
      <!--    </div>-->
    </section>

  </article>
<% end %>

app/views/rooms/_list.html.erb
<section id="rooms-list">
  <h2 class="article-title">Rooms</h2>
  <div id="filterrific_results">

    <table class="table table-striped">
      <thead>
      <tr>
        <th>Property</th>
        <th>Room No. / Name</th>
        <th>List Price</th>
        <th>Ensuite</th>
  <!--      <th>Tenant Name</th>-->
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @rooms.uniq.each do |room| %>
        <%# @rooms.map(&:property_id).uniq.each do |room| %>
        <tr>
          <td><%= link_to room.property.property_name, room %></td>
          <td><%= room.number %></td>
          <td>&#163;<%= number_with_delimiter(sprintf("%.2f",room.list_price.to_f ), delimiter: ',') %></td>
          <td><%= room.ensuite %></td>
  <!--        <td><%#= get_tenants_name(room) %></td>-->
          <!-- <td><%= link_to (fa_icon 'sync-alt'), sync_property_room_path(@property, room), remote: true %></td> -->
          <td><%= link_to (fa_icon 'search'), room %></td>
          <td><%= link_to (fa_icon 'edit'), edit_room_path(room) %></td>
          <td><%= link_to (fa_icon 'trash'), room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
<!--    <div class="pagy-container">-->
      <%#= pagy_bootstrap_nav(@pagy).html_safe %>
<!--    </div>-->
  </div>
</section>

app/views/rooms/_rightmove_response.html.erb
<td><%= link_to (fa_icon 'sync-alt'), sync_rightmove_property_room_path(@property, @room), remote: true %></td>
<td>RightMove</td>
<td><%= @room.rightmove_response['create'].present? ? JSON.parse(@room.rightmove_response['create']) : 'N/A' %></td>
<td><%= @room.rightmove_response['create_error'].present? ? JSON.parse(@room.rightmove_response['create_error']) : 'N/A' %></td>
<td><%= @room.rightmove_response['delete'].present? ? JSON.parse(@room.rightmove_response['delete']) : 'N/A' %></td>
<td><%= @room.rightmove_response['delete_error'].present? ? JSON.parse(@room.rightmove_response['delete_error']) : 'N/A' %></td>

app/views/rooms/_sync.html.erb
<div class="modal-header">
  <h3 class="modal-title">Sync Property</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <article>
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Sync</th>
              <th>Type</th>
              <th>Create</th>
              <th>Create Error</th>
              <th>Delete</th>
              <th>Delete Error</th>
            </tr>
          </thead>
          <tbody>
            <tr id="rightmove_<%=@room.id %>">
              <%= render 'rightmove_response' %>
            </tr>
            <tr id="zoopla_<%= @room.id %>">
              <%= render 'zoopla_response' %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </article>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/rooms/_zoopla_response.html.erb
<td><%= link_to (fa_icon 'sync-alt'), sync_zoopla_property_room_path(@property, @room), remote: true %></td>
<td>Zoopla</td>
<td><%= @room.zoopla_response['create'].present? ? JSON.parse(@room.zoopla_response['create']) : 'N/A' %></td>
<td><%= @room.zoopla_response['create_error'].present? ? JSON.parse(@room.zoopla_response['create_error']) : 'N/A' %></td>
<td><%= @room.zoopla_response['delete'].present? ? JSON.parse(@room.zoopla_response['delete']) : 'N/A' %></td>
<td><%= @room.zoopla_response['delete_error'].present? ? JSON.parse(@room.zoopla_response['delete_error']) : 'N/A' %></td>

app/views/rooms/edit.html.erb
<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<div id="title-bar" class="sticky-top">
  <h1><%= "#{@property.property_name}"+'-'+t('.title') %></h1>
  <div class="actions d-flex btn-group justify-content-end push">
    <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
    <%= link_to t('.new'), new_property_room_path(@property), class: 'btn btn-primary' %>
  </div>
</div>

<%#= puts @filterrific.inspect %>
<%#= form_for_filterrific @filterrific, html: {class: 'filterrific-form'} do |f| %>
<!--  <div class="row">-->
<!--    <div class="col">-->
<!--      <span>Search</span>-->
      <%#= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control') %>
<!--    </div>-->

<!--    <div class="col">-->
<!--        <span>-->
<!--          Sort by-->
<!--        </span>-->
      <%#= f.select(:sorted_by, @filterrific.select_options[:sorted_by], {}, {class: 'form-control'}) %>
<!--    </div>-->

<!--    <div class="col text-right">-->
      <%#= link_to 'Reset filters', reset_filterrific_url, class: 'btn btn-arsenic' %>
<!--    </div>-->
<!--  </div>-->

<%# end %>

<article>
  <%= render( partial: 'list', locals: { properties: @rooms }) %>
</article>

<%= render 'shared/common_modal' %>

app/views/rooms/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { rooms: @rooms })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>
  <div id="title-bar" class="sticky-top">
    <h1><%= @room.property.property_name %></h1>
    <div class="actions d-flex btn-group justify-content-end push">
      <%= link_to 'Back', property_path(@room.property), class: 'btn btn-secondary' %>
      <%= link_to 'Edit', edit_room_path(@room), class: 'btn btn-success' %>
    </div>
  </div>

  <article>
    <section>
      <h3 class="article-title">Room Details</h3>
      <table class="table">
        <tbody>
        <tr>
          <td>Room Number:</td>
          <td><%= @room.number %></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td><%= @room.description %></td>
        </tr>
        <tr>
          <td>Dimensions:</td>
          <td><%= @room.dimensions %></td>
        </tr>
        <tr>
          <td>List Price:</td>
          <td>£<%= number_with_delimiter(sprintf("%.2f",@room.list_price.to_f), delimiter: ',') %></td>
        </tr>
        <tr>
          <td>Ensuite:</td>
          <td><%= yes_no @room.ensuite %></td>
        </tr>
        <tr>
          <td>Availability:</td>
          <td><%= yes_no @room.availability %></td>
        </tr>
        </tbody>

      </table>
    </section>

  </article>
</div>

app/views/rooms/sync.js.erb
$("#commonModal .modal-content").html("<%= j render 'sync' %>");
$("#commonModal").modal("show");

app/views/rooms/sync_rightmove.js.erb
$("#rightmove_<%=@room.id%>").html("<%= j render 'rightmove_response'%>")

app/views/rooms/sync_zoopla.js.erb
$("#zoopla_<%=@room.id%>").html("<%= j render 'zoopla_response'%>")